export const FETCH_DATA_PENDING = "FETCH_DATA_PENDING";
export const FETCH_DATA_FULLFILLED = "FETCH_DATA_FULLFILLED";
export const FETCH_DATA_REJECTED = "FETCH_DATA_REJECTED";
export const PATCH_DATA_PENDING = "PATCH_DATA_PENDING";
export const PATCH_DATA_FULLFILLED = "PATCH_DATA_FULLFILLED";
export const PATCH_DATA_REJECTED = "PATCH_DATA_REJECTED";
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

